apiVersion: batch/v1
kind: Job
metadata:
  name: sad-talker
spec:
  template:
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ai-server
      restartPolicy: Never
      containers:
        - name: sad-talker
          image: ccr.ccs.tencentyun.com/lwabish/sadtalker
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
            - mountPath: /app/SadTalker/results
              name: data
              subPath: sad-talker/result

