logLevel: "debug"
db:
  # sqlite/mysql
  driver: "sqlite"
  mysql: "root:root@tcp(localhost:3307)/ai-server?charset=utf8mb4&parseTime=True&loc=Local"
# 真实ai服务调用方式
# bare-metal
# cloud-native
mode: "bare-metal"
auth:
  tokenExpire: false
bareMetal:
  sadTalker:
    projectPath: /root/SadTalker
    pythonPath: /root/miniconda3/envs/sadtalker/bin/python
    extraArgs: []
  roop:
    projectPath: /root/roop
    pythonPath: /root/miniconda3/envs/roop/bin/python
    extraArgs: []
cloudNative:
  sadTalker:
    jobNamespace: default
